# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sundeep
tagline:          'Blog'
description:      'Notes and thoughts about all computer related stuff'
url:              http://sundeepb.github.io/blog/
baseurl:          /

author:
  name:           'Sundeep B'
  url:            https://twitter.com/sundeep_here

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/SundeepB/blog
